apiVersion: v1
kind: ConfigMap
metadata:
  name: darkswap-relay-config
  namespace: darkswap-production
data:
  config.toml: |
    [server]
    host = "0.0.0.0"
    port = 8080
    
    [relay]
    max_connections = 5000
    connection_timeout = 60
    
    [logging]
    level = "info"
    file = "/var/log/darkswap/relay.log"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: darkswap-relay
  namespace: darkswap-production
  labels:
    app: darkswap-relay
    environment: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: darkswap-relay
  template:
    metadata:
      labels:
        app: darkswap-relay
        environment: production
    spec:
      containers:
      - name: darkswap-relay
        image: darkswap/relay:${VERSION}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: config
          mountPath: /app/config.toml
          subPath: config.toml
        - name: logs
          mountPath: /var/log/darkswap
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "2000m"
            memory: "2Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: config
        configMap:
          name: darkswap-relay-config
      - name: logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: darkswap-relay
  namespace: darkswap-production
  labels:
    app: darkswap-relay
    environment: production
spec:
  selector:
    app: darkswap-relay
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: darkswap-relay
  namespace: darkswap-production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: darkswap-relay
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: darkswap-relay-pdb
  namespace: darkswap-production
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: darkswap-relay