global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "alert-rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "darkswap-daemon"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["darkswap-daemon:9100"]
    
  - job_name: "darkswap-relay"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["darkswap-relay:9101"]
    
  - job_name: "darkswap-web"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["darkswap-web:9102"]
    
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9080"]
    
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://darkswap.io
        - https://api.darkswap.io
        - https://ws.darkswap.io
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: "pushgateway"
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]

  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: "bitcoin-node"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["bitcoin-exporter:9332"]

remote_write:
  - url: "http://prometheus-remote-write:9201/api/v1/write"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 10
      capacity: 10000
    write_relabel_configs:
      - source_labels: [__name__]
        regex: 'go_.*'
        action: drop

remote_read:
  - url: "http://prometheus-remote-read:9201/api/v1/read"
    read_recent: true