version: '3.8'

services:
  relay:
    build:
      context: .
      dockerfile: Dockerfile
    image: darkswap-relay:latest
    container_name: darkswap-relay
    restart: unless-stopped
    ports:
      - "9002:9002"  # Signaling server
      - "9003:9003"  # WebRTC server
      - "9090:9090"  # Metrics server
    volumes:
      - ./config.toml:/app/config.toml
      - ./certs:/app/certs
    environment:
      - RUST_LOG=info
      - DARKSWAP_RELAY_ENABLE_METRICS=true
      - DARKSWAP_RELAY_ENABLE_AUTHENTICATION=false
      - DARKSWAP_RELAY_ENABLE_RATE_LIMITING=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - darkswap-network

  prometheus:
    image: prom/prometheus:latest
    container_name: darkswap-prometheus
    restart: unless-stopped
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - darkswap-network
    depends_on:
      - relay

  grafana:
    image: grafana/grafana:latest
    container_name: darkswap-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    networks:
      - darkswap-network
    depends_on:
      - prometheus

volumes:
  prometheus-data:
  grafana-data:

networks:
  darkswap-network:
    driver: bridge