[package]
name = "darkswap-support"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.11"
bytes = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"

[build-dependencies]
prost-build = "0.11"